# --- Global Settings ---
seed: 42
checkpoint_dir: "/kaggle/working/DS201/Lab_2/checkpoints"

# --- Dataset Definitions ---
datasets:
  vinafood: # Chỉ cần định nghĩa vinafood
    train_path: "/kaggle/input/vinafood21/VinaFood21/train"
    test_path: "/kaggle/input/vinafood21/VinaFood21/test"
    classes: 21

# --- Model Definitions ---
models:
  GoogleNet: models.GoogleNet.GoogleNet # Chỉ cần định nghĩa GoogleNet

# --- Experiment Definition ---
experiments:
  - name: "GoogleNet_ViNaFood"
    model: "GoogleNet"
    dataset: "vinafood"
    hyperparameters:
      epochs: 80
      lr: 0.001
      weight_decay: 0
      batch_size: 32
      optimizer: "Adam"
      step_size: 20
      gamma: 0.1
      optimizer_params: {}