# --- Global Settings ---
seed: 42
checkpoint_dir: "kaggle/working/DS201/checkpoints"

# --- Dataset Definitions ---
datasets:
  monkey: # Chỉ cần định nghĩa monkey
    train_path: "/kaggle/input/monkey/train"
    test_path: "/kaggle/input/monkey/test"
    classes: 10

# --- Model Definitions ---
models:
  GoogleNet: models.GoogleNet.GoogleNet # Chỉ cần định nghĩa GoogleNet

# --- Experiment Definition ---
experiments:
  - name: "GoogleNet_Monkey"
    model: "GoogleNet"
    dataset: "monkey"
    hyperparameters:
      epochs: 250
      lr: 0.001
      weight_decay: 0.00001
      batch_size: 32
      optimizer: "Adam"
      step_size: 30
      gamma: 0.1
      optimizer_params: {}