# --- Global Settings ---
seed: 42
checkpoint_dir: "/kaggle/working/DS201/Lab_2/checkpoints"

# --- Dataset Definitions ---
datasets:
  vinafood: # Chỉ cần định nghĩa vinafood
    train_path: "/kaggle/input/vinafood21/VinaFood21/train"
    test_path: "/kaggle/input/vinafood21/VinaFood21/test"
    classes: 21

# --- Model Definitions ---
models:
  Resnet50: models.Resnet50.Resnet50 # Chỉ cần định nghĩa Resnet50

# --- Experiment Definition ---
experiments:
  - name: "Resnet50_ViNaFood"
    model: "ResNet50"
    dataset: "vinafood"
    hyperparameters:
      epochs: 100
      early_stop_patience: 20
      lr: 0.0001
      weight_decay: 0.00001
      batch_size: 32
      optimizer: "Adam"
      step_size: 30
      gamma: 0.1
      optimizer_params: {}