# --- Global Settings ---
seed: 42
checkpoint_dir: "/kaggle/working/DS201/Lab_2/checkpoints"

# --- Dataset Definitions ---
datasets:
  vinafood: # Chỉ cần định nghĩa vinafood
    train_path: "/kaggle/input/vinafood21/VinaFood21/train"
    test_path: "/kaggle/input/vinafood21/VinaFood21/test"
    classes: 21

# --- Model Definitions ---
models:
  Resnet18: models.Resnet18.Resnet18 # Chỉ cần định nghĩa Resnet18

# --- Experiment Definition ---
experiments:
  - name: "Resnet18_ViNaFood"
    model: "ResNet18"
    dataset: "vinafood"
    hyperparameters:
      epochs: 60
      lr: 0.0001
      weight_decay: 0
      batch_size: 32
      optimizer: "Adam"
      step_size: 30
      gamma: 0.1
      optimizer_params: {}