# --- Global Settings ---
seed: 42
checkpoint_dir: "/kaggle/working/DS201/Lab_2/checkpoints"

# --- Dataset Definitions ---
datasets:
  mnist: # Chỉ cần định nghĩa mnist
    train_images: "/kaggle/input/mnist-dataset/train-images.idx3-ubyte"
    train_labels: "/kaggle/input/mnist-dataset/train-labels.idx1-ubyte"
    test_images: "/kaggle/input/mnist-dataset/t10k-images.idx3-ubyte"
    test_labels: "/kaggle/input/mnist-dataset/t10k-labels.idx1-ubyte"
    classes: 10

# --- Model Definitions ---
models:
  LeNet: models.LeNet.LeNet # Chỉ cần định nghĩa LeNet

# --- Experiment Definition ---
experiments:
  - name: "LeNet_MNIST"
    model: "LeNet"
    dataset: "mnist"
    hyperparameters:
      epochs: 1
      early_stop_patience: 10
      lr: 0.001
      weight_decay: 0.0001
      batch_size: 128
      optimizer: "Adam"
      step_size: 25
      gamma: 0.1
      optimizer_params: {}
